#https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
#Add commit message [skip ci] to skip workflow 
name : Workflow Status
on : push 
jobs: 
    output-wf:
        runs-on : ubuntu-latest
        outputs:
            op1: ${{steps.step1.output.demo}}
        steps:
            - name : hello-world
              id : step1
              run: echo "demo=Hello World" >> $GITHUB_OUTPUT
    input-wf:
        runs-on : ubuntu-latest
        needs: output-wf
        steps:
            - name : input-from-output-wf
              run  : echo "Output from above steps ${{needs.steps.outputs.demo}}"
