#https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
#Add commit message [skip ci] to skip workflow
name : Workflow Status
on : push 
jobs: 
    skip-wf:
        runs-on : ubuntu-latest
        steps:
            - name : hello world
              run: echo "Hello World"
